name: scraping news
on:
  schedule:
  - cron: '0 */6 * * *'
  push:
    branches:
      - development
jobs:
  scraping:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59-vanadium
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: Scraping News
      env:
        URL: "https://www.pref.miyazaki.lg.jp/kenko/hoken/kansensho/covid19/hassei.html"
        SELENIUM_HOST: localhost
        TZ: Asia/Tokyo
      run: |
        gem install bundler
        bundle update --bundler
        bundle install
        ruby scraping.rb

    - name: Scraping Data
      env:
        URL: "https://www.pref.miyazaki.lg.jp/kenko/hoken/kansensho/covid19/hassei.html"
        SELENIUM_HOST: localhost
        TZ: Asia/Tokyo
      run: |
        ruby scraping_data.rb

